# Generated by Django 5.0.7 on 2024-07-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telegram_id', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('vk_id', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='VK ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('wishes', models.CharField(max_length=300, verbose_name='Желания')),
                ('room', models.PositiveIntegerField(blank=True, null=True, verbose_name='Комната')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Курс')),
                ('gifts_to', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Дарит(кому)')),
                ('has_giver', models.BooleanField(default=False)),
                ('current_priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MailList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('message', models.CharField(max_length=1000, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Изображение')),
                ('members', models.ManyToManyField(to='secret_santa.user')),
            ],
            options={
                'verbose_name': 'Рассылки',
            },
        ),
    ]
