# Generated by Django 5.0.7 on 2024-07-25 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_santa', '0002_alter_maillist_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gifts_to',
            field=models.IntegerField(blank=True, null=True, verbose_name='Дарит(кому)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='giver_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secret_santa.user', verbose_name='Дарит(кому)'),
        ),
    ]
