# Generated by Django 5.0.7 on 2024-07-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_santa', '0004_alter_user_gifts_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='maillist',
            name='schedueld_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
