# Generated by Django 5.0.7 on 2024-07-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_santa', '0005_maillist_schedueld_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maillist',
            name='schedueld_time',
        ),
        migrations.AddField(
            model_name='maillist',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='maillist',
            name='members',
            field=models.ManyToManyField(to='secret_santa.user', verbose_name='Участники'),
        ),
    ]
